### PR TITLE
Update source code

### PR DESCRIPTION
**Pull request by maxzhen**

### CODE REVIEW

**Comment by keryell** [comment]
This seems to break my system.
First the NPU does not work anymore just after compilation and install (without rebooting):
```
[Fri Feb 16 15:37:09 2024] amdxdna 0000:66:00.1: (Develop) IOMMU mode is 0
[Fri Feb 16 15:37:10 2024] amdxdna 0000:66:00.1: fw return error 0x5(Error unknown)
[Fri Feb 16 15:37:10 2024] amdxdna 0000:66:00.1: failed to validate fw, ret -5
[Fri Feb 16 15:37:10 2024] amdxdna 0000:66:00.1: npu_hw_init: failed to create psp
[Fri Feb 16 15:37:10 2024] amdxdna 0000:66:00.1: npu_init: XDNA NPU hardware init failed -22
[Fri Feb 16 15:37:10 2024] amdxdna 0000:66:00.1: amdxdna_probe: hardware init failed, ret -22
[Fri Feb 16 15:37:10 2024] amdxdna: probe of 0000:66:00.1 failed with error -22

rkeryell@rk-xsj:~/Xilinx/Projects/AIE/xdna-driver/build (main)$ ./example_build/example_noop_test /lib/firmware/amdnpu/1502/validate.xclbin
Host test code start...
Host test code is creating device object...
Segmentation fault (core dumped)
```

But it gets worse after rebooting because it breaks my display:
```
[    4.755779] [drm] Initialized amdgpu 3.57.0 20150101 for 0000:65:00.0 on minor 0
[    4.795339] fbcon: amdgpudrmfb (fb0) is primary device
[    5.638353] amdgpu 0000:65:00.0: [drm] fb0: amdgpudrmfb frame buffer device
[   21.828364] RIP: 0010:amdgpu_device_rreg+0xf3/0x120 [amdgpu]
[   21.828520] Code: 75 1d f6 83 f0 ec 03 00 10 74 14 48 8b 83 e0 08 04 00 48 8d 78 18 e8 9c 06 87 e7 85 c0 75 10 4c 03 a3 e0 08 00 00 45 8b 24 24 <e9> 63 ff ff ff 48 89 df 31 d2 44 89 f6 e8 8b 49 13 00 41 89 c4 48
[   21.828521] RSP: 0018:ffffb2a882e33a58 EFLAGS: 00000282
[   21.828523] RAX: 0000000000000000 RBX: ffff8ba216980000 RCX: 0000000000000000
[   21.828524] RDX: 0000000000000000 RSI: 0000000000058a68 RDI: ffff8ba216980000
[   21.828525] RBP: ffffb2a882e33a80 R08: 0000000000000000 R09: 0000000000000000
[   21.828526] R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000000
[   21.828527] R13: 0000000000000000 R14: 000000000001629a R15: ffff8ba216980000
[   21.828531]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.828533]  ? delay_halt+0x40/0x80
[   21.828536]  smu_cmn_send_smc_msg_with_param+0x180/0x2f0 [amdgpu]
[   21.828759]  smu_cmn_update_table+0x8d/0x180 [amdgpu]
[   21.828961]  smu_cmn_get_metrics_table+0x48/0xe0 [amdgpu]
[   21.829152]  smu_v13_0_4_read_sensor+0x27b/0x310 [amdgpu]
[   21.829346]  smu_read_sensor+0xab/0x270 [amdgpu]
[   21.829538]  amdgpu_dpm_read_sensor+0x70/0xb0 [amdgpu]
[   21.829753]  amdgpu_hwmon_get_sensor_generic+0x97/0xf0 [amdgpu]
[   21.829962]  amdgpu_hwmon_show_vddgfx+0x39/0x80 [amdgpu]
[   21.830161]  dev_attr_show+0x1a/0x70
[   21.830164]  sysfs_kf_seq_show+0xa4/0x120
[   21.830168]  kernfs_seq_show+0x24/0x40
[   21.830170]  seq_read_iter+0x12f/0x4b0
[   21.830174]  kernfs_fop_read_iter+0x152/0x1a0
[   21.830176]  ? security_file_permission+0x5f/0x70
[   21.830180]  vfs_read+0x1fb/0x330
[   21.830185]  ksys_read+0x73/0x100
[   21.830188]  __x64_sys_read+0x19/0x30
[   21.830190]  do_syscall_64+0x5d/0xf0
[   21.830192]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830193]  ? exit_to_user_mode_prepare+0x39/0x190
[   21.830196]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830197]  ? syscall_exit_to_user_mode+0x37/0x60
[   21.830200]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830201]  ? do_syscall_64+0x6c/0xf0
[   21.830203]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830205]  ? exit_to_user_mode_prepare+0x39/0x190
[   21.830207]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830209]  ? syscall_exit_to_user_mode+0x37/0x60
[   21.830211]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830212]  ? do_syscall_64+0x6c/0xf0
[   21.830214]  ? srso_alias_return_thunk+0x5/0xfbef5
[   21.830215]  ? do_syscall_64+0x6c/0xf0
[   21.830218]  entry_SYSCALL_64_after_hwframe+0x6e/0x7
[   26.020458] amdgpu 0000:65:00.0: amdgpu: SMU: I'm not done with your previous command: SMN_C2PMSG_66:0x0000000F SMN_C2PMSG_82:0x00000007
[   26.021069] amdgpu 0000:65:00.0: amdgpu: Failed to export SMU metrics table!
[   30.751816] amdgpu 0000:65:00.0: amdgpu: SMU: I'm not done with your previous command: SMN_C2PMSG_66:0x0000000F SMN_C2PMSG_82:0x00000007
[   30.752417] amdgpu 0000:65:00.0: amdgpu: Failed to export SMU metrics table!
[   31.312848] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, signaled seq=25, emitted seq=27
[   31.313616] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
[   31.314239] amdgpu 0000:65:00.0: amdgpu: GPU reset begin!
[   35.481389] amdgpu 0000:65:00.0: amdgpu: SMU: I'm not done with your previous command: SMN_C2PMSG_66:0x0000000F SMN_C2PMSG_82:0x00000007
[   35.481398] amdgpu 0000:65:00.0: amdgpu: Failed to export SMU metrics table!
```
Curious.

**Comment by Joel-De** [comment]
I seem to be experiencing this issue as well on Ubuntu 22.04.

**Comment by maxzhen** [comment]
@Joel-De and @keryell , could you help to check if the firmware installed on your systems are corrupted? The md5sum should show:
17e56bc5040dcd74f0b579751e764aca  ./ipu.sbin.1.2.0.280

**Comment by keryell** [comment]
That sounds a place to dig:
```
-<%>- md5sum /lib/firmware/amdnpu/1502/npu.sbin
55ec925a5d01bcf32fc27c798cc22eb4  /lib/firmware/amdnpu/1502/npu.sbin
```

**Comment by maxzhen** [comment]
> That sounds like a place to dig:
> 
> ```
> -<%>- md5sum /lib/firmware/amdnpu/1502/npu.sbin
> 55ec925a5d01bcf32fc27c798cc22eb4  /lib/firmware/amdnpu/1502/npu.sbin
> ```
> 
> I will look more carefully to the install process.

Thanks for checking! The firmware link is broken. I'm fixing it now. We'll also update the pipeline test script to make sure the link is validated properly to prevent this accident in the future.

**Comment by maxzhen** [comment]
Should be fixed by PR#20.

**Comment by Joel-De** [comment]
Works for me as well now. Thanks @maxzhen!

**Pull request merged**
